apiVersion: v1
kind: Pod
metadata:
  name: "podsconfigmap"
  namespace: default
  labels:
    app: "alphineapps"
spec:
  containers:
  - name: alphineapps
    image: alpine
    command: ["sleep", "3600"] 
    env:
    - name: dbserver
      valueFrom:
        configMapKeyRef:
          name: configdatabase
          key: databasehost
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: appvolume
      mountPath: /apps/data
  volumes:
    - name: appvolume
      hostPath:
        path: /mnt/appdata
 