apiVersion: v1
kind: Secret
metadata:
  name: secretdbserverconn
  namespace: default
type: Opaque
data:
  dbserverhostname: "bXlzcWxzZXJ2ZXI6MTQzMy5henVyZS5jb20="      #"mysqlserver:1433.azure.com"
  port: "MTQzMw=="      #"1433"
  username : "YWRtaW4="        #"admin"
  password : "cGFzc3dvcmQxMjM0"  #   password1234
  # Example:
  # password: {{ .Values.password | b64enc }}