apiVersion: v1
kind: Pod
metadata:
  name: "nginxpodappps"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: nginxapps
    image: "nginx"   
    env:
    - name: dbservername
      valueFrom:
        secretKeyRef:          
          name: secretdbserverconn
          key: dbserverhostname         
    - name: dbport
      valueFrom:
        secretKeyRef:          
          name: secretdbserverconn
          key: port  
    - name: dbusername
      valueFrom:
        secretKeyRef:          
          name: secretdbserverconn
          key: username
    - name: dbpassword
      valueFrom:
        secretKeyRef:          
          name: secretdbserverconn
          key: password                    
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: nginxvolume
      mountPath: /app/nginxapps
  volumes:
    - name: nginxvolume
      hostPath:
        path: /mnt/nginxdata/
  