apiVersion: v1
kind: Service
metadata:
  name: dotnetappservice
  namespace: default
spec:
  selector:
    app: dotnetappsdeploy
  type: LoadBalancer
  
  ports:
  - name: dotnetappsdeploy
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    