apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginxappsdeploy
  namespace: default
  labels:
    app:  nginxapps
spec:
  selector:
    matchLabels:
      app: nginxapps
  replicas: 3  
  template:
    metadata:
      labels:
        app:  nginxapps
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginxapps
        image:  nginx 
        ports:
        - containerPort:  80
          name:  nginxapps
        volumeMounts:
        - name: nginxvolume
          mountPath: /apps/nginxdata
      volumes:
        - name: nginxvolume
          hostPath:
            path: /mnt/nginxvolume
      restartPolicy: Always