apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replicasdotnet
  labels:
    app: dotnetappsreplicas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dotnetappsreplicas
  template:
    metadata:
      labels:
        app: dotnetappsreplicas
    spec:
      containers:
      - name: dotnetappsreplicas
        image: 11122233345/webappsdocker
        
            




# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: MYAPP
#   labels:
#     app: MYAPP
# spec:
#   # modify replicas according to your case
#   replicas: 3
#   selector:
#     matchLabels:
#       app: MYAPP
#   template:
#     metadata:
#       labels:
#         app: MYAPP
#     spec:
#       containers:
#       - name: MYAPP
#         image: nginx/nginx
#         ports:
#         - name: web
#           containerPort:  80
#           protocol: TCP
#         env:
#         - name: NGX_VERSION
#           value: 1.16.1
#         volumeMounts:
#         - name: localtime
#           mountPath: /etc/localtime
#       volumes:
#         - name: localtime
#           hostPath:
#             path: /usr/share/zoneinfo/Asia/Shanghai