apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginxrollbackdeployment
  namespace: default
  labels:
    app:  nginxrollback
spec:
  selector:
    matchLabels:
      app: nginxrollback
  replicas: 3  
  template:
    metadata:
      labels:
        app:  nginxrollback
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginxrollback
        image:  nginx:1.17        
        ports:
        - containerPort:  80
          name:  nginxrollback
        volumeMounts:
        - name: nginxvolume
          mountPath: /apps/nginxdata
      volumes:
        - name: nginxvolume
          hostPath:
            path: /mydata/nginxvolume
     